version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.7.18-management-alpine@sha256:d1e707e654b7a1b40ed8aa145fa2a31477a47ebbdb856d08dd7e508b0c3b19bc
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 5s
      retries: 20
    ports:
      - "5672:5672"

networks:
  default:
    name: cloudbuild
    external: true
