version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.7.18-management-alpine@sha256:d1e707e654b7a1b40ed8aa145fa2a31477a47ebbdb856d08dd7e508b0c3b19bc
    ports:
      - "5672:5672"

networks:
  default:
    name: cloudbuild
